#image: docker.io/ibrgvz/docker-ubuntu-ppa-stm32-builder:latest

before_script:
  - echo "Running on ${CI_RUNNER_DESCRIPTION} (#${CI_RUNNER_ID})"
  - apt-get update
  - apt-get install make


cli:
  tags:
    - lab
  script:
    - cd examples/hello-world/ && make BOARD=inga-white
