#image: docker.io/ibrgvz/docker-ubuntu-ppa-stm32-builder:latest

# wget OR curl should be enough
before_script:
  - echo "Running on ${CI_RUNNER_DESCRIPTION} (#${CI_RUNNER_ID})"
  #- apt-get update
  #- apt-get install --assume-yes make curl unzip avr-libc binutils-avr gcc-avr avrdude

cli:
  tags:
    - inga
  script:
    - ls -lah /dev/inga/*
    - cd examples/hello-world/ && make PORT=/dev/inga/node-A502C3XN BOARD=inga-red flash
    - cd -
    - cd tests/unittests/
    - make PORT=/dev/inga/node-A502C3XN BOARD=inga-red tests-core flash
