before_script:
  - echo "Running on ${CI_RUNNER_DESCRIPTION} (#${CI_RUNNER_ID})"
  #- apt-get update
  #- apt-get install --assume-yes make curl unzip avr-libc binutils-avr gcc-avr avrdude

inga:
  tags:
    - inga
  script:
    - python3 -m serial.tools.list_ports -v
    - export PORT=`python3 -m serial.tools.list_ports -v 2>/dev/null | grep -B 2 'A502C3XN' | head -n 1`
    - echo $PORT
    - cd examples/hello-world/
    - make PORT=${PORT} BOARD=inga-red flash
    #- make PORT=${PORT} BOARD=inga-red term &
    #- PID=$!
    #- echo ${PID}
    #- ../../dist/tools/inga_tool/inga_tool -r -d ${PORT}
    #- sleep 5; kill -9 $PID
    - cd -
    - cd tests/unittests/
    - make PORT=${PORT} BOARD=inga-red tests-core flash
    #- make PORT=${PORT} BOARD=inga-red term &
    #- PID=$!
    #- echo ${PID}
    #- ../../dist/tools/inga_tool/inga_tool -r -d ${PORT}
    #- sleep 5; kill -9 $PID
buildtest:
  tags:
    - docker
  image: riot/riotbuild
  script:
    #- apt-get update
    #- apt-get install --assume-yes build-essential
    #- apt-get install --assume-yes make curl unzip avr-libc binutils-avr gcc-avr avrdude
    #- apt-get install --assume-yes binutils-msp430 gcc-msp430 gdb-msp430 msp430-libc msp430mcu mspdebug
    - cd examples/hello-world/
    - make buildtest
