USEMODULE += inga-common

# Flasher is board-dependent!
export FLASHER = avrdude
export FFLAGS = -c jtag2isp -p m1284p -P usb -u -U flash:w:$(HEXFILE)
export INCLUDES += -I$(RIOTBOARD)/inga-common/include/

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTBOARD)/inga-common/Makefile.include
