## the cpu to build for
export CPU = atmega1284p

# flash tool configuration
export OFLAGS = -j .text -j .data -O ihex
#export CFLAGS += -mmcu=atmega1284p -O0
export CFLAGS += -D__DELAY_BACKWARD_COMPATIBLE__=1

# set default port depending on operating system
PORT_LINUX ?= $(firstword $(sort $(wildcard /dev/ttyUSB*)))
# setup serial terminal
export BAUD ?= 19200
include $(RIOTMAKE)/tools/serial.inc.mk
