USEMODULE += inga-common

# Flasher is board-dependent!
#export FLASHER = $(RIOTBOARD)/inga-common/tools/inga_tool/inga_tool -d $(PORT) -r && avrdude
# New flash tool
include $(RIOTMAKE)/tools/inga_tool.inc.mk

export INCLUDES += -I$(RIOTBOARD)/inga-common/include/

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTBOARD)/inga-common/Makefile.include
