USEMODULE += inga-common

# Flasher is board dependent!
export FLASHER = $(RIOTBOARD)/inga-common/tools/inga_tool/inga_tool -d $(PORT) -r && avrdude
export FFLAGS =-c avr109 -p m1284p -P $(PORT) -b 230400 -u -U flash:w:$(HEXFILE)

export INCLUDES += -I$(RIOTBOARD)/inga-common/include/

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTBOARD)/inga-common/Makefile.include
