USEMODULE += inga-common

# Use flash tool
include $(RIOTMAKE)/tools/inga_tool.inc.mk

export INCLUDES += -I$(RIOTBOARD)/inga-common/include/

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTBOARD)/inga-common/Makefile.include
